parameters:
- name: runTimeParameter
  displayName: runTimeParameter
  default: test1
  values:
  - test1
  - test2
  - test3

- name: test
  displayName: Run Tests?
  type: boolean
  default: false

trigger: none

jobs:
- job: build
  displayName: Build and Test
  pool: 
    vmImage: ubuntu-latest
  steps:
  - script: echo building $(Build.BuildNumber)
  - ${{ if eq(parameters.test, true) }}:
    - script: echo ${{ parameters.runTimeParameter }} $(pullRequest)